coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

ignore:
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/test/**"